language: ruby
sudo: false
rvm:
- 2.1.10
- 2.2.10
- 2.3.8
- 2.4.5
- 2.5.3
- 2.6.0-rc1
before_install:
- gem update bundler
after_script:
- './bin/run-rubocop.sh'
notifications:
  email:
  - ogataken@gmail.com
env:
  global:
    secure: MNPyYmOIa7mHfXELfUG0oYUxIDq3GYRhpWCZwg8q0JrstFO1Zex6db/Epb/WaQwaduG95Du6LsZ/gi+NZt6r1Ei5iLo1pzaKCOziHh8xizpAk5Bnvf5JeDN/SmUgfMMgpW3IK33HLQtPcMuvAKj6ybKa1Kbbh1XBMFQo8vaSCvQ=
